apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aisalkyn85/kafka-enterprise-orders.git'
    targetRevision: main
    path: k8s/charts/webapp
    helm:
      values: |
        frontendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/web-frontend:latest"
        backendImage: "ghcr.io/aisalkyn85/kafka-enterprise-orders/web-backend:latest"
        backendPort: 8000
        ghcr:
          enabled: false
        ingress:
          host: "orders.jumptotech.dev"
        couchbase:
          host: "couchbase.your-domain.com"
          bucket: "order_analytics"
          username: "Administrator"
          password: ""
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
