apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aisalkyn85/kafka-enterprise-orders.git'
    targetRevision: main
    path: k8s/charts/webapp
    helm:
      values: |
        frontendImage: "ghcr.io/Aisalkyn85/kafka-enterprise-orders/web-frontend:latest"
        backendImage: "ghcr.io/Aisalkyn85/kafka-enterprise-orders/web-backend:latest"

        domain: "orders.jumptotech.dev"

        couchbase:
          host: "couchbase.your-domain"
          bucket: "order_analytics"
          username: "Administrator"
          password: "password"

  destination:
    server: https://kubernetes.default.svc
    namespace: webapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

